version: "3.7"

services:

  webserver:
    image: nginx:alpine
    container_name: ads-catalog-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 20004:80
    environment:
      - SHELL=/bin/ash
    depends_on:
      - php-fpm

  php-fpm:
    build: .docker/php
    container_name: ads-catalog-php-fpm
    working_dir: /application
    volumes:
      - .:/application

  database:
    container_name: ads-catalog-database
    image: mysql:5.6
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

networks:
  default:
    external:
      name: nginx_proxy

